image: tmaier/docker-compose:latest
 
#Build-app:
#  stage: build
#  script:
#    - echo 'deploying app in QA server'
    
Testing 1/2:
  stage: test
  script:
    - docker-compose -f local-docker-compose.yml up --abort-on-container-exit --exit-code-from lippia
  artifacts:
    paths:
      - target/reports/
#Testing 2/2:
#  script: 
#    - echo 'another test process'
 
#Deploy:
#  stage: deploy
#  script: 
#    - echo 'deploying app in custom server'